### ISSUE TITLE
ProductId MUST be a URN - how to cope with URLs and URI, e.g. defined in IEC 61406-1:2022

### ISSUE THREAD

**Issue by StenGruener** [wbcsd/data-exchange-protocol#12]
Hi all,

in our industry we are increasingly using IEC 61406 identification links which are urls, e.g., https://id.abb/123456?SN=123456, those are also printed as QR codes on the devices.

How could we make use of the WBCSD protocols it is requiring to use URNs?

BR
Sten

**Comment by zeitgeist** [comment]
Hello Sten,

my sincere apologies for this (ridiculously) late follow up. 

Different approaches are possible to encode URLs into URNs, which for instance is proposed in the digital passport space: <img width="1728" alt="Screenshot 2022-02-09 at 18 18 57" src="https://github.com/wbcsd/data-exchange-protocol/assets/38831/3416cf00-0b3d-4898-8ffb-5fbd009f070b"> [With additional details given [here](https://gs1.eu/wp-content/uploads/2022/08/Digital_Product_Passport_Architecture_GS1inEurope_March_2022.pdf)]

I personally can imagine different approaches how to map identification links you mentioned in the current tech specs.

If you are interested in driving this further, 
1. please reach out to either me or the PACT team (pact@wbcsd.org), or
2. please take a look at the [ADR process](https://github.com/wbcsd/data-exchange-protocol/blob/main/DECISION-MAKING-PROCESS.md) to propose a change to the tech specs to cover your case.
