### ISSUE TITLE
Some property names are not in lower camel case.

### ISSUE THREAD

**Issue by s2-matsuo** [wbcsd/data-exchange-protocol#31]
Hi, 

I found that the property name "p**C**fExcludingBiogenic" and "p**C**fIncludingBiogenic" are not in lower camel case.
Are these what you intended?
https://wbcsd.github.io/data-exchange-protocol/v2/#dt-carbonfootprint-properties

**Comment by JohnVonNeumann** [comment]
Hey @s2-matsuo I have noticed this in the past also and it's been verified that it is intended, I don't remember the exact reasoning but there was a user requirement type reason for it.

**Comment by mill6-plat6aux** [comment]
Hello @JohnVonNeumann 
I know CamelCase is a rule that capitalizes the concatenation of words, but what words does `pCfExcludingBiogenic` concatenate?
It looks like `pcf + excluding + biogenic` to me...

**Comment by JohnVonNeumann** [comment]
Here is it @mill6-plat6aux :

https://github.com/wbcsd/data-exchange-protocol/pull/7

**Comment by raimundo-henriques** [comment]
Dear all,

Thank you very much for this discussion and apologies for the delay in our reply.

As indicated in PR #7, this spelling was applied after discussion with solution providers. Changing it would be a backwards-breaking change and would, therefore, require an ADR, to be discussed in the context of the Tech WG. Let us know if you want to move forward with this and if you need our support.

Best regards,
