### ISSUE TITLE
geographicScope

### ISSUE THREAD

**Issue by sbunker** [wbcsd/data-exchange-protocol#75]
The [open api schema](https://api.pathfinder.sine.dev/openapi.json) lists the 3 geography properties under a `geographicScope` object. The [technical spec](https://wbcsd.github.io/tr/2024/data-exchange-protocol-20240410/) does not mention the `geographicScope` object.

**Comment by raimundo-henriques** [comment]
Dear @sbunker ,

Thanks for the issue. 

As you correctly point out, there should be no `geographicScope` object. The geographic scope is defined as specified [here](https://wbcsd.github.io/tr/2024/data-exchange-protocol-20240410/#dt-carbonfootprint-scope)

We will fix this ASAP. 

Thank you
